# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LKImageViewExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'YYWebImage', '~> 1.0.5'
   pod 'SDWebImage', '~> 4.3.0'

  # Pods for LKImageViewExample

end
